//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountChart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountChart()
        {
            this.AccountChart1 = new HashSet<AccountChart>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AccountTypeId { get; set; }
        public Nullable<long> AccountSubTypeId { get; set; }
        public Nullable<long> AccountSpecificTypeId { get; set; }
        public Nullable<long> CashFlowClassId { get; set; }
        public string AccountNormId { get; set; }
        public Nullable<long> ParentAccountChartId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool SoleProprietorship { get; set; }
        public bool Partnership { get; set; }
        public bool Corporation { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> IndustryId { get; set; }
    
        public virtual AccountNorm AccountNorm { get; set; }
        public virtual AccountSpecificType AccountSpecificType { get; set; }
        public virtual AccountSubType AccountSubType { get; set; }
        public virtual AccountType AccountType { get; set; }
        public virtual CashFlowClass CashFlowClass { get; set; }
        public virtual Industry Industry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountChart> AccountChart1 { get; set; }
        public virtual AccountChart AccountChart2 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
