//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCompany
    {
        public long Id { get; set; }
        public Nullable<long> MemoId { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public string AltAccountNo { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public decimal OpenBalance { get; set; }
        public Nullable<System.DateTime> OpenBalanceDate { get; set; }
        public decimal Balance { get; set; }
        public decimal TrialBalance { get; set; }
        public bool IsInactive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public long AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Company Company { get; set; }
        public virtual Memo Memo { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
