//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovedVendor
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long VendorId { get; set; }
        public bool IsQualified { get; set; }
        public bool IsPending { get; set; }
        public Nullable<System.DateTime> QualifiedSinceDate { get; set; }
        public Nullable<System.DateTime> InitialAssessmentDate { get; set; }
        public Nullable<System.DateTime> NextReAssessmentDate { get; set; }
        public Nullable<int> ReAssessmentMonths { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
