//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.Equipments = new HashSet<Equipment>();
            this.Machines = new HashSet<Machine>();
            this.MachineTools = new HashSet<MachineTool>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int AssetTypeId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> PurchasedOn { get; set; }
        public Nullable<decimal> SalvageValue { get; set; }
        public Nullable<int> DepreciationMethodId { get; set; }
        public Nullable<int> UsefulLifeYears { get; set; }
        public Nullable<int> RecurringMaintenanceMonths { get; set; }
        public bool IsMaintained { get; set; }
        public Nullable<System.DateTime> NextMaintenance { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<long> AssetAccountId { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<long> ApprovedByUserId { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsSent { get; set; }
        public bool IsForeignCurrency { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<long> CurrencyExchangeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> SpecificationId { get; set; }
    
        public virtual AssetType AssetType { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual DepreciationMethod DepreciationMethod { get; set; }
        public virtual Account Account { get; set; }
        public virtual Company Company { get; set; }
        public virtual CurrencyExchange CurrencyExchange { get; set; }
        public virtual Department Department { get; set; }
        public virtual Item Item { get; set; }
        public virtual Location Location { get; set; }
        public virtual Specification Specification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine> Machines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineTool> MachineTools { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
