//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assembly
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assembly()
        {
            this.AssemblyDetails = new HashSet<AssemblyDetails>();
        }
    
        public long Id { get; set; }
        public Nullable<long> DocumentSetId { get; set; }
        public string AssemblyName { get; set; }
        public string Revision { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsVoid { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<long> ApprovedByUserId { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsSent { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> SpecificationId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CurrencyExchange CurrencyExchange { get; set; }
        public virtual Item Item { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyDetails> AssemblyDetails { get; set; }
    }
}
