//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attachment()
        {
            this.Attachment1 = new HashSet<Attachment>();
            this.DocumentLists = new HashSet<DocumentList>();
            this.ManufacturedComponents = new HashSet<ManufacturedComponent>();
            this.ProductBuilds = new HashSet<ProductBuild>();
            this.ManufacturedSubComponents = new HashSet<ManufacturedSubComponent>();
        }
    
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public long DocumentTypeId { get; set; }
        public Nullable<long> OriginatorCompanyId { get; set; }
        public Nullable<long> ParentAttachmentId { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public string DocumentTitle { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string Description { get; set; }
        public string AttachmentPath { get; set; }
        public string AttachmentObject { get; set; }
        public bool IsExpirable { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] AttachmentFile { get; set; }
        public Nullable<int> TotalChild { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Company Company1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachment1 { get; set; }
        public virtual Attachment Attachment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentList> DocumentLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturedComponent> ManufacturedComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBuild> ProductBuilds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturedSubComponent> ManufacturedSubComponents { get; set; }
    }
}
