//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public long AccountId { get; set; }
        public long CurrencyId { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public string AccountNo { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> BeginningBalance { get; set; }
        public Nullable<decimal> Balance { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Account Account { get; set; }
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
