//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySetting
    {
        public long Id { get; set; }
        public bool MultiCurrency { get; set; }
        public string TinNo { get; set; }
        public bool IsVatSystem { get; set; }
        public bool IsFiscalYear { get; set; }
        public Nullable<System.DateTime> FiscalYearStart { get; set; }
        public Nullable<System.DateTime> FiscalYearEnd { get; set; }
        public string CountryCodeId { get; set; }
        public string WebSite { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> DefaultCurrencyId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public bool IsOperationMode { get; set; }
        public bool IsNew { get; set; }
        public string TimeZoneCode { get; set; }
    
        public virtual CountryCode CountryCode { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
