//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyWorkCalendar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyWorkCalendar()
        {
            this.EmployeeWorkCalendars = new HashSet<EmployeeWorkCalendar>();
        }
    
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public System.DateTime CalendarDate { get; set; }
        public string MonthName { get; set; }
        public string ShortMonthName { get; set; }
        public string DayOfWeek { get; set; }
        public string ShortWeekName { get; set; }
        public short Quarter { get; set; }
        public short Month { get; set; }
        public short Day { get; set; }
        public short Week { get; set; }
        public bool IsWeekDay { get; set; }
        public bool IsLegalHoliday { get; set; }
        public bool IsSpecialHoliday { get; set; }
        public string HolidayDescription { get; set; }
        public bool IsPayDay { get; set; }
        public int Year { get; set; }
        public string DailyPayrollRateMultiplierId { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeWorkCalendar> EmployeeWorkCalendars { get; set; }
    }
}
