//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardPaymentMethod
    {
        public long Id { get; set; }
        public long CurrencyId { get; set; }
        public string Name { get; set; }
        public string Method { get; set; }
        public string BankName { get; set; }
        public string EncryptedCardNumber { get; set; }
        public short NumberOfDigits { get; set; }
        public long LastDisplayDigits { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string EncryptedSecuritySecurityCode { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
