//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentListTemplate
    {
        public long Id { get; set; }
        public long DocumentSetTemplateId { get; set; }
        public string Description { get; set; }
        public long ItemSequence { get; set; }
        public bool IsRequired { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<long> ReferenceId { get; set; }
        public string DocumentTitle { get; set; }
        public long DocumentTypeId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<int> MinSecurityClearanceId { get; set; }
    
        public virtual SecurityClearance SecurityClearance { get; set; }
        public virtual DocumentSetTemplate DocumentSetTemplate { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Location Location { get; set; }
    }
}
