//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeWorkCalendar
    {
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public long EmployeeId { get; set; }
        public long CompanyWorkCalendarId { get; set; }
        public System.DateTime CalendarDate { get; set; }
        public bool IsNotAvailable { get; set; }
        public Nullable<long> WorkShiftId { get; set; }
        public Nullable<long> TimeClockId { get; set; }
        public string TimeClockStatusId { get; set; }
        public Nullable<decimal> DayHours { get; set; }
        public Nullable<decimal> NightHours { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyWorkCalendar CompanyWorkCalendar { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
