//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDailyHour
    {
        public long Id { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public long EmployeeId { get; set; }
        public System.DateTime CalendarDate { get; set; }
        public System.DateTime StartWorkingTime { get; set; }
        public System.DateTime EndWorkingTime { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> NAbsent { get; set; }
        public Nullable<int> NLate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
