//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSkillMatrixDetails
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> QualifiedOn { get; set; }
        public Nullable<System.DateTime> IsQualified { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<long> ApprovedByUserId { get; set; }
        public string Remarks { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeeSkillMatrix EmployeeSkillMatrix { get; set; }
        public virtual EmployeeSkillsRatings EmployeeSkillsRatings { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual MachineType MachineType { get; set; }
    }
}
