//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPTestEntities : DbContext
    {
        public ERPTestEntities()
            : base("name=ERPTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConversionUnit> ConversionUnit { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<JobPriority> JobPriority { get; set; }
        public virtual DbSet<PrimeLoad> PrimeLoad { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Bom> Bom { get; set; }
        public virtual DbSet<BomDetails> BomDetails { get; set; }
        public virtual DbSet<BomItemType> BomItemType { get; set; }
        public virtual DbSet<BomMfgConsumable> BomMfgConsumable { get; set; }
        public virtual DbSet<BomOtherCostDetails> BomOtherCostDetails { get; set; }
        public virtual DbSet<EngineeringChangeStatus> EngineeringChangeStatus { get; set; }
        public virtual DbSet<EngineeringPhase> EngineeringPhase { get; set; }
        public virtual DbSet<FamilyRouter> FamilyRouter { get; set; }
        public virtual DbSet<FamilyRouterLink> FamilyRouterLink { get; set; }
        public virtual DbSet<ManufacturedComponent> ManufacturedComponent { get; set; }
        public virtual DbSet<ManufacturedSubComponent> ManufacturedSubComponent { get; set; }
        public virtual DbSet<ProductBuild> ProductBuild { get; set; }
        public virtual DbSet<ProductBuildBomLink> ProductBuildBomLink { get; set; }
        public virtual DbSet<ProductBuildDetails> ProductBuildDetails { get; set; }
        public virtual DbSet<ProductBuildDevelopmentLabor> ProductBuildDevelopmentLabor { get; set; }
        public virtual DbSet<ProductBuildDraft> ProductBuildDraft { get; set; }
        public virtual DbSet<ProductBuildInvestment> ProductBuildInvestment { get; set; }
        public virtual DbSet<ProductBuildMaterials> ProductBuildMaterials { get; set; }
        public virtual DbSet<ProductBuildRouterLink> ProductBuildRouterLink { get; set; }
        public virtual DbSet<Router> Router { get; set; }
        public virtual DbSet<RouterAction> RouterAction { get; set; }
        public virtual DbSet<RouterDetails> RouterDetails { get; set; }
        public virtual DbSet<RouterDetailsLink> RouterDetailsLink { get; set; }
        public virtual DbSet<RouterOutsideDetails> RouterOutsideDetails { get; set; }
        public virtual DbSet<RouterProcess> RouterProcess { get; set; }
        public virtual DbSet<RouterProcessDetails> RouterProcessDetails { get; set; }
        public virtual DbSet<RouterType> RouterType { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CurrencyExchange> CurrencyExchange { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemStatus> ItemStatus { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeSkillMatrix> EmployeeSkillMatrix { get; set; }
        public virtual DbSet<EmployeeSkillMatrixDetails> EmployeeSkillMatrixDetails { get; set; }
        public virtual DbSet<EmployeeSkillsRatings> EmployeeSkillsRatings { get; set; }
        public virtual DbSet<WorkShift> WorkShift { get; set; }
        public virtual DbSet<WorkShiftSchedule> WorkShiftSchedule { get; set; }
        public virtual DbSet<ItemLocation> ItemLocation { get; set; }
        public virtual DbSet<ItemLotBin> ItemLotBin { get; set; }
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<MachineType> MachineType { get; set; }
        public virtual DbSet<StockMovement> StockMovement { get; set; }
        public virtual DbSet<StockMovementDetails> StockMovementDetails { get; set; }
        public virtual DbSet<Assembly> Assembly { get; set; }
        public virtual DbSet<AssemblyDetails> AssemblyDetails { get; set; }
        public virtual DbSet<MachineFixture> MachineFixture { get; set; }
        public virtual DbSet<MachineTool> MachineTool { get; set; }
        public virtual DbSet<MachineToolType> MachineToolType { get; set; }
        public virtual DbSet<MfgConsumable> MfgConsumable { get; set; }
        public virtual DbSet<MfgConsumableType> MfgConsumableType { get; set; }
        public virtual DbSet<WorkCenter> WorkCenter { get; set; }
        public virtual DbSet<WorkCenterGroup> WorkCenterGroup { get; set; }
        public virtual DbSet<WorkCenterType> WorkCenterType { get; set; }
        public virtual DbSet<WorkOrder> WorkOrder { get; set; }
        public virtual DbSet<WorkOrderDetails> WorkOrderDetails { get; set; }
    }
}
