//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyRouterLink
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public Nullable<long> FamilyRouterId { get; set; }
        public Nullable<long> RouterId { get; set; }
        public Nullable<decimal> TargetQuantity { get; set; }
        public Nullable<long> UnitId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
    
        public virtual FamilyRouter FamilyRouter { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Router Router { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
