//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemSale()
        {
            this.ForeignItemSales = new HashSet<ForeignItemSale>();
        }
    
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public long SalesDescriptionId { get; set; }
        public Nullable<long> SalesAccountId { get; set; }
        public decimal SalesPrice { get; set; }
        public long UnitId { get; set; }
        public decimal StockToSalesConversion { get; set; }
        public bool IsSalesWithVat { get; set; }
        public decimal SalesWeight { get; set; }
        public bool IsSerialized { get; set; }
        public bool HasWarraty { get; set; }
        public long WarrantyDays { get; set; }
        public Nullable<System.DateTime> LastSold { get; set; }
        public bool Inactive { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ShorrtDescription { get; set; }
        public long SalesWeightUnitId { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual Account Account { get; set; }
        public virtual Company Company { get; set; }
        public virtual Description Description { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForeignItemSale> ForeignItemSales { get; set; }
        public virtual Item Item { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
