//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStatu
    {
        public long Id { get; set; }
        public Nullable<decimal> ReorderPoint { get; set; }
        public Nullable<decimal> MinAutoOrder { get; set; }
        public Nullable<decimal> BeginBalance { get; set; }
        public Nullable<decimal> OnHand { get; set; }
        public Nullable<decimal> OnPurchase { get; set; }
        public Nullable<decimal> InProduction { get; set; }
        public Nullable<decimal> TotalAvailable { get; set; }
        public Nullable<decimal> Allocated { get; set; }
        public Nullable<decimal> Reserved { get; set; }
        public Nullable<decimal> TotalRequired { get; set; }
        public Nullable<decimal> Scrap { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> Receive { get; set; }
        public Nullable<decimal> Returns { get; set; }
        public Nullable<decimal> AdjustmentIn { get; set; }
        public Nullable<decimal> AdjustmentOut { get; set; }
        public Nullable<decimal> NetUsed { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
