//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBuyXref
    {
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public long ItemId { get; set; }
        public long VendorId { get; set; }
        public string SupplierPartNo { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ItemBuyXrefDescriptionId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Description Description { get; set; }
        public virtual Item Item { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
