//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBuy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemBuy()
        {
            this.BomDetails = new HashSet<BomDetail>();
            this.ManufacturedSubComponents = new HashSet<ManufacturedSubComponent>();
            this.ForeignItemBuys = new HashSet<ForeignItemBuy>();
            this.MfgConsumables = new HashSet<MfgConsumable>();
        }
    
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public long BuyDescriptionId { get; set; }
        public Nullable<int> ProcurementTypeId { get; set; }
        public decimal BuyPrice { get; set; }
        public long UnitId { get; set; }
        public decimal StockToBuyConversion { get; set; }
        public bool IsBuyWithVat { get; set; }
        public decimal BuyWeight { get; set; }
        public Nullable<System.DateTime> LastPurchased { get; set; }
        public bool Inactive { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ReplacedByItemId { get; set; }
        public bool IsObsolete { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ShortDescription { get; set; }
        public long BuyWeightUnitId { get; set; }
        public Nullable<long> PreferredVendorId { get; set; }
    
        public virtual ProcurementType ProcurementType { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BomDetail> BomDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturedSubComponent> ManufacturedSubComponents { get; set; }
        public virtual Company Company { get; set; }
        public virtual Description Description { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForeignItemBuy> ForeignItemBuys { get; set; }
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MfgConsumable> MfgConsumables { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
