//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturedComponent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManufacturedComponent()
        {
            this.BomDetails = new HashSet<BomDetails>();
            this.ManufacturedSubComponent = new HashSet<ManufacturedSubComponent>();
            this.ManufacturedSubComponent1 = new HashSet<ManufacturedSubComponent>();
            this.ProductBuildDetails = new HashSet<ProductBuildDetails>();
            this.Router = new HashSet<Router>();
            this.RouterProcess = new HashSet<RouterProcess>();
        }
    
        public long Id { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public Nullable<long> DocumentSetId { get; set; }
        public Nullable<long> ApprovedByUserId { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<long> InventoryAccountId { get; set; }
        public Nullable<long> CogsAccountId { get; set; }
        public string BarCode { get; set; }
        public Nullable<long> DrawingAttachementId { get; set; }
        public string ComponentNo { get; set; }
        public Nullable<System.DateTime> ModifieddOn { get; set; }
        public Nullable<long> DescriptionId { get; set; }
        public string PictureUrl { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BomDetails> BomDetails { get; set; }
        public virtual EngineeringChangeStatus EngineeringChangeStatus { get; set; }
        public virtual EngineeringPhase EngineeringPhase { get; set; }
        public virtual Company Company { get; set; }
        public virtual CurrencyExchange CurrencyExchange { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturedSubComponent> ManufacturedSubComponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturedSubComponent> ManufacturedSubComponent1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBuildDetails> ProductBuildDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Router> Router { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouterProcess> RouterProcess { get; set; }
    }
}
