//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturedComponent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManufacturedComponent()
        {
            this.BomDetails = new HashSet<BomDetail>();
            this.ManufacturedSubComponents = new HashSet<ManufacturedSubComponent>();
            this.ManufacturedSubComponents1 = new HashSet<ManufacturedSubComponent>();
            this.ProductBuildDetails = new HashSet<ProductBuildDetail>();
            this.Routers = new HashSet<Router>();
            this.RouterProcesses = new HashSet<RouterProcess>();
        }
    
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public Nullable<int> EngineeringPhaseId { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public Nullable<long> UnitId { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<long> CurrencyExchangeId { get; set; }
        public Nullable<long> DocumentSetId { get; set; }
        public Nullable<long> ApprovedByUserId { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<long> ComponentItemId { get; set; }
        public Nullable<long> InventoryAccountId { get; set; }
        public Nullable<long> CogsAccountId { get; set; }
        public string BarCode { get; set; }
        public Nullable<long> DrawingAttachementId { get; set; }
        public string ComponentNo { get; set; }
        public Nullable<System.DateTime> ModifieddOn { get; set; }
        public string EngineeringChangeStatusId { get; set; }
        public Nullable<long> DescriptionId { get; set; }
        public string PictureUrl { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BomDetail> BomDetails { get; set; }
        public virtual EngineeringChangeStatu EngineeringChangeStatu { get; set; }
        public virtual EngineeringPhase EngineeringPhase { get; set; }
        public virtual Company Company { get; set; }
        public virtual CurrencyExchange CurrencyExchange { get; set; }
        public virtual Description Description { get; set; }
        public virtual Account Account { get; set; }
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturedSubComponent> ManufacturedSubComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManufacturedSubComponent> ManufacturedSubComponents1 { get; set; }
        public virtual Account Account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBuildDetail> ProductBuildDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Router> Routers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouterProcess> RouterProcesses { get; set; }
        public virtual Attachment Attachment { get; set; }
        public virtual DocumentSet DocumentSet { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
