//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialIssuance
    {
        public long Id { get; set; }
        public long ItemId { get; set; }
        public System.DateTime IssuanceDate { get; set; }
        public long IssuedByEmployeeId { get; set; }
        public long WorkOrderId { get; set; }
        public decimal QuantityIssued { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<long> ApprovedByUserId { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsSent { get; set; }
        public bool IsForeignCurrency { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<long> CurrencyExchangeId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> QuantityReturned { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Company Company { get; set; }
        public virtual CurrencyExchange CurrencyExchange { get; set; }
        public virtual Item Item { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
