//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelEntities : DbContext
    {
        public ModelEntities()
            : base("name=ModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountNorm> AccountNorms { get; set; }
        public virtual DbSet<AccountSpecificType> AccountSpecificTypes { get; set; }
        public virtual DbSet<AccountSubType> AccountSubTypes { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<ApprovalType> ApprovalTypes { get; set; }
        public virtual DbSet<AssetType> AssetTypes { get; set; }
        public virtual DbSet<AuthorizationType> AuthorizationTypes { get; set; }
        public virtual DbSet<CashFlowClass> CashFlowClasses { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<ConversionUnit> ConversionUnits { get; set; }
        public virtual DbSet<CountryCode> CountryCodes { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<DepreciationMethod> DepreciationMethods { get; set; }
        public virtual DbSet<EmailType> EmailTypes { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<ItemClass> ItemClasses { get; set; }
        public virtual DbSet<JobPriority> JobPriorities { get; set; }
        public virtual DbSet<LocationClass> LocationClasses { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<MessagePriority> MessagePriorities { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<PhoneType> PhoneTypes { get; set; }
        public virtual DbSet<ProcurementType> ProcurementTypes { get; set; }
        public virtual DbSet<SalesTaxType> SalesTaxTypes { get; set; }
        public virtual DbSet<SecurityClearance> SecurityClearances { get; set; }
        public virtual DbSet<ServiceMode> ServiceModes { get; set; }
        public virtual DbSet<ShippingMovement> ShippingMovements { get; set; }
        public virtual DbSet<ShippingPayMode> ShippingPayModes { get; set; }
        public virtual DbSet<ShippingTerm> ShippingTerms { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<VatType> VatTypes { get; set; }
        public virtual DbSet<Bom> Boms { get; set; }
        public virtual DbSet<BomDetail> BomDetails { get; set; }
        public virtual DbSet<BomItemType> BomItemTypes { get; set; }
        public virtual DbSet<BomMfgConsumable> BomMfgConsumables { get; set; }
        public virtual DbSet<BomOtherCostDetail> BomOtherCostDetails { get; set; }
        public virtual DbSet<Diagram> Diagrams { get; set; }
        public virtual DbSet<EngineeringChangeStatu> EngineeringChangeStatus { get; set; }
        public virtual DbSet<EngineeringPhase> EngineeringPhases { get; set; }
        public virtual DbSet<FamilyRouter> FamilyRouters { get; set; }
        public virtual DbSet<FamilyRouterLink> FamilyRouterLinks { get; set; }
        public virtual DbSet<ManufacturedComponent> ManufacturedComponents { get; set; }
        public virtual DbSet<ManufacturedSubComponent> ManufacturedSubComponents { get; set; }
        public virtual DbSet<ProductBuild> ProductBuilds { get; set; }
        public virtual DbSet<ProductBuildBomLink> ProductBuildBomLinks { get; set; }
        public virtual DbSet<ProductBuildDetail> ProductBuildDetails { get; set; }
        public virtual DbSet<ProductBuildDevelopmentLabor> ProductBuildDevelopmentLabors { get; set; }
        public virtual DbSet<ProductBuildDraft> ProductBuildDrafts { get; set; }
        public virtual DbSet<ProductBuildInvestment> ProductBuildInvestments { get; set; }
        public virtual DbSet<ProductBuildMaterial> ProductBuildMaterials { get; set; }
        public virtual DbSet<ProductBuildRouterLink> ProductBuildRouterLinks { get; set; }
        public virtual DbSet<Router> Routers { get; set; }
        public virtual DbSet<RouterAction> RouterActions { get; set; }
        public virtual DbSet<RouterDetail> RouterDetails { get; set; }
        public virtual DbSet<RouterOutsideDetail> RouterOutsideDetails { get; set; }
        public virtual DbSet<RouterProcess> RouterProcesses { get; set; }
        public virtual DbSet<RouterProcessDetail> RouterProcessDetails { get; set; }
        public virtual DbSet<RouterType> RouterTypes { get; set; }
        public virtual DbSet<WorkInstruction> WorkInstructions { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountChart> AccountCharts { get; set; }
        public virtual DbSet<AccountCompany> AccountCompanies { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<ApprovedVendor> ApprovedVendors { get; set; }
        public virtual DbSet<AutoNumber> AutoNumbers { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyLogo> CompanyLogoes { get; set; }
        public virtual DbSet<CompanySetting> CompanySettings { get; set; }
        public virtual DbSet<CompanyToAddress> CompanyToAddresses { get; set; }
        public virtual DbSet<CompanyToPerson> CompanyToPersons { get; set; }
        public virtual DbSet<CompanyWorkCalendar> CompanyWorkCalendars { get; set; }
        public virtual DbSet<CreditCardPaymentMethod> CreditCardPaymentMethods { get; set; }
        public virtual DbSet<CurrencyExchange> CurrencyExchanges { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerType> CustomerTypes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Description> Descriptions { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<ForeignItemBuy> ForeignItemBuys { get; set; }
        public virtual DbSet<ForeignItemSale> ForeignItemSales { get; set; }
        public virtual DbSet<FormSpecificationCategory> FormSpecificationCategories { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemBuy> ItemBuys { get; set; }
        public virtual DbSet<ItemBuyXref> ItemBuyXrefs { get; set; }
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<ItemImage> ItemImages { get; set; }
        public virtual DbSet<ItemSale> ItemSales { get; set; }
        public virtual DbSet<ItemSalesXref> ItemSalesXrefs { get; set; }
        public virtual DbSet<ItemStatu> ItemStatus { get; set; }
        public virtual DbSet<ItemSubcategory> ItemSubcategories { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationCategory> LocationCategories { get; set; }
        public virtual DbSet<LocationCategoryDetail> LocationCategoryDetails { get; set; }
        public virtual DbSet<LocationDetail> LocationDetails { get; set; }
        public virtual DbSet<Memo> Memos { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonImage> PersonImages { get; set; }
        public virtual DbSet<PersonToAddress> PersonToAddresses { get; set; }
        public virtual DbSet<PersonToEmail> PersonToEmails { get; set; }
        public virtual DbSet<PersonToPhone> PersonToPhones { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<ProductLine> ProductLines { get; set; }
        public virtual DbSet<Specification> Specifications { get; set; }
        public virtual DbSet<SpecificationCategory> SpecificationCategories { get; set; }
        public virtual DbSet<SpecificationCategoryDetail> SpecificationCategoryDetails { get; set; }
        public virtual DbSet<SpecificationDetail> SpecificationDetails { get; set; }
        public virtual DbSet<Subsidiary> Subsidiaries { get; set; }
        public virtual DbSet<TaxInfo> TaxInfoes { get; set; }
        public virtual DbSet<TaxRegistration> TaxRegistrations { get; set; }
        public virtual DbSet<UserColorSetting> UserColorSettings { get; set; }
        public virtual DbSet<VatRegistration> VatRegistrations { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorType> VendorTypes { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<AssetInvestmentAction> AssetInvestmentActions { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
        public virtual DbSet<ItemLocation> ItemLocations { get; set; }
        public virtual DbSet<ItemLotBin> ItemLotBins { get; set; }
        public virtual DbSet<ItemSerial> ItemSerials { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<MachineType> MachineTypes { get; set; }
        public virtual DbSet<MaterialIssuance> MaterialIssuances { get; set; }
        public virtual DbSet<Physical> Physicals { get; set; }
        public virtual DbSet<PhysicalDetail> PhysicalDetails { get; set; }
        public virtual DbSet<StockMovement> StockMovements { get; set; }
        public virtual DbSet<StockMovementDetail> StockMovementDetails { get; set; }
        public virtual DbSet<Assembly> Assemblies { get; set; }
        public virtual DbSet<AssemblyDetail> AssemblyDetails { get; set; }
        public virtual DbSet<MachineFixture> MachineFixtures { get; set; }
        public virtual DbSet<MachineTool> MachineTools { get; set; }
        public virtual DbSet<MachineToolType> MachineToolTypes { get; set; }
        public virtual DbSet<MfgConsumable> MfgConsumables { get; set; }
        public virtual DbSet<MfgConsumableType> MfgConsumableTypes { get; set; }
        public virtual DbSet<ToolSet> ToolSets { get; set; }
        public virtual DbSet<ToolSetDetail> ToolSetDetails { get; set; }
        public virtual DbSet<WorkCenter> WorkCenters { get; set; }
        public virtual DbSet<WorkCenterGroup> WorkCenterGroups { get; set; }
        public virtual DbSet<WorkCenterType> WorkCenterTypes { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<WorkOrderDetail> WorkOrderDetails { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<DocumentList> DocumentLists { get; set; }
        public virtual DbSet<DocumentListTemplate> DocumentListTemplates { get; set; }
        public virtual DbSet<DocumentRevision> DocumentRevisions { get; set; }
        public virtual DbSet<DocumentSet> DocumentSets { get; set; }
        public virtual DbSet<DocumentSetTemplate> DocumentSetTemplates { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<DailyRate> DailyRates { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeDailyHour> EmployeeDailyHours { get; set; }
        public virtual DbSet<EmployeeDailySchedule> EmployeeDailySchedules { get; set; }
        public virtual DbSet<EmployeeSkillMatrix> EmployeeSkillMatrices { get; set; }
        public virtual DbSet<EmployeeSkillMatrixDetail> EmployeeSkillMatrixDetails { get; set; }
        public virtual DbSet<EmployeeSkillsRating> EmployeeSkillsRatings { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<EmployeeWorkCalendar> EmployeeWorkCalendars { get; set; }
    }
}
