//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physical
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Physical()
        {
            this.PhysicalDetails = new HashSet<PhysicalDetail>();
        }
    
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Memo { get; set; }
        public Nullable<long> LocationId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<long> CountedByEmployeeId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsPosted { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<long> ApprovedByUserId { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsSent { get; set; }
        public bool IsForeignCurrency { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<long> CurrencyExchangeId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ReferenceNo { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Company Company { get; set; }
        public virtual CurrencyExchange CurrencyExchange { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalDetail> PhysicalDetails { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
