//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBuildInvestment
    {
        public long Id { get; set; }
        public Nullable<long> ItemSequence { get; set; }
        public Nullable<int> AssetInvestmentActionId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> RecoveredOverFirstNoParts { get; set; }
        public Nullable<decimal> EstimatedDevelopmentInvestmentCost { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> EstimatedMaintenanceRecurringCost { get; set; }
        public Nullable<decimal> RecurMaintAfterPartsProduce { get; set; }
    
        public virtual ProductBuild ProductBuild { get; set; }
        public virtual ProductBuild ProductBuild1 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
