//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBuildDraft
    {
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> ProductBuildId { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsVoid { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<long> CurrencyExchangeId { get; set; }
        public Nullable<double> PercentScrap { get; set; }
        public Nullable<decimal> EstimatedTaxes { get; set; }
        public Nullable<decimal> EstimatedDuties { get; set; }
        public Nullable<decimal> EstimatedShippingCost { get; set; }
        public Nullable<decimal> EstimatedLandedCost { get; set; }
        public Nullable<decimal> EstimatedAdditionalOverhead { get; set; }
        public Nullable<decimal> EstimatedProcessCost { get; set; }
        public Nullable<decimal> EstimatedMaterialCost { get; set; }
        public Nullable<decimal> EstimatedPackagingCost { get; set; }
        public Nullable<decimal> EstimatedMfgConsumableCost { get; set; }
        public Nullable<decimal> EstimatedDevelopmentLaborCost { get; set; }
        public Nullable<decimal> EstimatedDevelopmentInvestmentCost { get; set; }
        public Nullable<decimal> EstimatedOtherBomCost { get; set; }
        public Nullable<decimal> EstimatedTotalCost { get; set; }
        public Nullable<decimal> CalculatedCostPerUnit { get; set; }
        public Nullable<long> UnitId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> BuildQuantity { get; set; }
        public Nullable<long> ItemId { get; set; }
    
        public virtual ProductBuild ProductBuild { get; set; }
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Item Item { get; set; }
    }
}
