//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouterProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RouterProcess()
        {
            this.ProductBuildDetails = new HashSet<ProductBuildDetail>();
            this.RouterDetails = new HashSet<RouterDetail>();
            this.RouterProcessDetails = new HashSet<RouterProcessDetail>();
        }
    
        public long Id { get; set; }
        public string ProcessName { get; set; }
        public string ProcessDescription { get; set; }
        public string EngineeringChangeStatusId { get; set; }
        public Nullable<long> ManufacturedComponentId { get; set; }
        public Nullable<long> WorkInstructionId { get; set; }
        public Nullable<decimal> EstimatedFixedProcessCost { get; set; }
        public Nullable<decimal> EstimatedVariableCostPiece { get; set; }
        public bool IsExported { get; set; }
        public Nullable<int> LeadTimeDays { get; set; }
        public Nullable<decimal> EstimatedTaxes { get; set; }
        public Nullable<decimal> EstimatedDuties { get; set; }
        public Nullable<decimal> EstimatedShippingCost { get; set; }
        public Nullable<decimal> EstimatedLandedCost { get; set; }
        public Nullable<decimal> EstimatedAdditionalOverhead { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<long> CurrencyExchangeId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public bool IsCompleted { get; set; }
    
        public virtual EngineeringChangeStatu EngineeringChangeStatu { get; set; }
        public virtual ManufacturedComponent ManufacturedComponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBuildDetail> ProductBuildDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouterDetail> RouterDetails { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouterProcessDetail> RouterProcessDetails { get; set; }
    }
}
