//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouterDetailsLink
    {
        public long Id { get; set; }
        public long RouterId { get; set; }
        public long HeadRouterDetailsId { get; set; }
        public Nullable<long> TailRouterDetailsId { get; set; }
        public Nullable<long> ModifiedbyEmployeeId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Router Router { get; set; }
        public virtual RouterDetail RouterDetail { get; set; }
        public virtual RouterDetail RouterDetail1 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
