//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouterDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RouterDetails()
        {
            this.WorkOrderDetails = new HashSet<WorkOrderDetails>();
            this.RouterDetailsLink = new HashSet<RouterDetailsLink>();
            this.RouterDetailsLink1 = new HashSet<RouterDetailsLink>();
        }
    
        public long Id { get; set; }
        public Nullable<long> OperationSequence { get; set; }
        public Nullable<double> PercentOverlap { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ProcessName { get; set; }
    
        public virtual Router Router { get; set; }
        public virtual Router Router1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderDetails> WorkOrderDetails { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual RouterProcess RouterProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouterDetailsLink> RouterDetailsLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouterDetailsLink> RouterDetailsLink1 { get; set; }
    }
}
