//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouterProcessDetail
    {
        public long Id { get; set; }
        public Nullable<long> RouterProcessId { get; set; }
        public Nullable<long> OperationSequence { get; set; }
        public long WorkCenterId { get; set; }
        public string OperationDescription { get; set; }
        public Nullable<decimal> QuantityOperators { get; set; }
        public Nullable<decimal> EstimatedSetupTime { get; set; }
        public Nullable<long> SetupUnitId { get; set; }
        public Nullable<decimal> EstimatedSetupHour { get; set; }
        public Nullable<long> RunUnitId { get; set; }
        public Nullable<decimal> EstimatedMachineRuntime { get; set; }
        public Nullable<long> MachineUnitId { get; set; }
        public Nullable<decimal> EstimatedMachineRuntimeHour { get; set; }
        public bool IsSkipOperation { get; set; }
        public string EngineeringChangeStatusId { get; set; }
        public Nullable<double> PercentOverlap { get; set; }
        public Nullable<long> WorkInstructionId { get; set; }
        public Nullable<long> WorkCenterGroupId { get; set; }
        public Nullable<decimal> QuantitySetters { get; set; }
        public Nullable<decimal> EstimatedSetupHourlyRate { get; set; }
        public Nullable<decimal> EstimatedSetupCost { get; set; }
        public Nullable<decimal> EstimatedRunTimePiece { get; set; }
        public Nullable<decimal> EstimatedRuntimeHourPiece { get; set; }
        public Nullable<decimal> EstimatedRuntimeHourlyRate { get; set; }
        public Nullable<decimal> EstimatedRuntimeCostPiece { get; set; }
        public Nullable<decimal> EstimatedMachineRuntimeHourlyRate { get; set; }
        public Nullable<decimal> EstimatedMachineRuntimeCost { get; set; }
        public Nullable<decimal> EstimatedTeardownTime { get; set; }
        public Nullable<long> TeardownUnitId { get; set; }
        public Nullable<decimal> EstimatedTeardownHour { get; set; }
        public Nullable<decimal> EstimatedTeardownHourlyRate { get; set; }
        public Nullable<decimal> EstimatedTeardownCost { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<long> CurrencyExchangeId { get; set; }
        public Nullable<double> EstimatedLaborOverheadFactor { get; set; }
        public Nullable<decimal> EstimatedLaborOverheadCost { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<long> MachineFixtureId { get; set; }
    
        public virtual EngineeringChangeStatu EngineeringChangeStatu { get; set; }
        public virtual RouterProcess RouterProcess { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual WorkCenterGroup WorkCenterGroup { get; set; }
        public virtual WorkCenter WorkCenter { get; set; }
    }
}
