//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Router
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Router()
        {
            this.FamilyRouterLink = new HashSet<FamilyRouterLink>();
            this.ProductBuildDevelopmentLabor = new HashSet<ProductBuildDevelopmentLabor>();
            this.ProductBuildRouterLink = new HashSet<ProductBuildRouterLink>();
            this.Router1 = new HashSet<Router>();
            this.RouterDetails = new HashSet<RouterDetails>();
            this.RouterDetails1 = new HashSet<RouterDetails>();
            this.RouterDetailsLink = new HashSet<RouterDetailsLink>();
            this.RouterOutsideDetails = new HashSet<RouterOutsideDetails>();
        }
    
        public long Id { get; set; }
        public Nullable<long> RevisionNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> DocumentSetId { get; set; }
        public bool IsObsolete { get; set; }
        public Nullable<System.DateTime> ObsoleteDate { get; set; }
        public bool IsVoid { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<long> ApprovedByUserId { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsSent { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TargetQuantity { get; set; }
        public Nullable<decimal> MinQuantity { get; set; }
        public string RouterCode { get; set; }
        public string Revision { get; set; }
        public Nullable<long> WorkInstructionId { get; set; }
        public string PictureUrl { get; set; }
        public Nullable<decimal> EstimatedProcessCost { get; set; }
        public bool IsOutsideProcess { get; set; }
        public bool IsExported { get; set; }
        public Nullable<int> LeadTimeDays { get; set; }
        public Nullable<decimal> EstimatedTaxes { get; set; }
        public Nullable<decimal> EstimatedDuties { get; set; }
        public Nullable<decimal> EstimatedShippingCost { get; set; }
        public Nullable<decimal> EstimatedLandedCost { get; set; }
        public Nullable<decimal> PurchaseOrderQuantity { get; set; }
        public Nullable<decimal> EstimatedAdditionalOverhead { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> DiagramId { get; set; }
        public bool IsCompleted { get; set; }
        public decimal OperationPlanYieldPercent { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual EngineeringChangeStatus EngineeringChangeStatus { get; set; }
        public virtual EngineeringPhase EngineeringPhase { get; set; }
        public virtual FamilyRouter FamilyRouter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyRouterLink> FamilyRouterLink { get; set; }
        public virtual ManufacturedComponent ManufacturedComponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBuildDevelopmentLabor> ProductBuildDevelopmentLabor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBuildRouterLink> ProductBuildRouterLink { get; set; }
        public virtual Company Company { get; set; }
        public virtual CurrencyExchange CurrencyExchange { get; set; }
        public virtual Item Item { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Router> Router1 { get; set; }
        public virtual Router Router2 { get; set; }
        public virtual RouterAction RouterAction { get; set; }
        public virtual RouterType RouterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouterDetails> RouterDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouterDetails> RouterDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouterDetailsLink> RouterDetailsLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouterOutsideDetails> RouterOutsideDetails { get; set; }
    }
}
