//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTaxType
    {
        public long Id { get; set; }
        public Nullable<long> AccountId { get; set; }
        public string TaxRegionCode { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string TaxRegionName { get; set; }
        public string ZipCode { get; set; }
        public decimal CombinedRate { get; set; }
        public Nullable<decimal> StateRate { get; set; }
        public Nullable<decimal> CountyRate { get; set; }
        public Nullable<decimal> CityRate { get; set; }
        public Nullable<decimal> SpecialRate { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
