//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationDetail
    {
        public long Id { get; set; }
        public long SpecificationId { get; set; }
        public string SpecificationName { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public string SpecificationValue { get; set; }
        public int ItemSequence { get; set; }
    
        public virtual Specification Specification { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
