//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovementDetail
    {
        public long Id { get; set; }
        public long StockMovementId { get; set; }
        public long ItemId { get; set; }
        public Nullable<long> ItemLotBinId { get; set; }
        public Nullable<long> FromItemLocationId { get; set; }
        public Nullable<long> ToItemLocationId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ItemLocation ItemLocation { get; set; }
        public virtual ItemLocation ItemLocation1 { get; set; }
        public virtual ItemLotBin ItemLotBin { get; set; }
        public virtual StockMovement StockMovement { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
