//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderDetails
    {
        public long Id { get; set; }
        public Nullable<decimal> OrderedQuantity { get; set; }
        public Nullable<decimal> ProducedQuantity { get; set; }
        public Nullable<decimal> ScrapQuantity { get; set; }
        public Nullable<decimal> EstimatedMaterialCost { get; set; }
        public Nullable<decimal> EstimatedLaborCost { get; set; }
        public Nullable<decimal> EstimatedOverheadCost { get; set; }
        public Nullable<decimal> EstimatedToolingCost { get; set; }
        public Nullable<decimal> EstimatedProductionConsumablesCost { get; set; }
        public Nullable<decimal> EstimatedPackagingCost { get; set; }
        public Nullable<decimal> MachineCost { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> OperationSequence { get; set; }
    
        public virtual RouterDetails RouterDetails { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
