//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrder()
        {
            this.ScheduledWorkOrders = new HashSet<ScheduledWorkOrder>();
            this.WorkOrderDetails = new HashSet<WorkOrderDetail>();
        }
    
        public long Id { get; set; }
        public Nullable<long> SalesOrderId { get; set; }
        public Nullable<System.DateTime> ScheduledProductionStartDate { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public bool IsVoid { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<long> ApprovedByUserId { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsSent { get; set; }
        public bool IsForeignCurrency { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<long> CurrencyExchangeId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> DocumentSetId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public long CustomerId { get; set; }
        public Nullable<System.DateTime> TargetCompletionDate { get; set; }
        public Nullable<long> ProductBuildId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsClosed { get; set; }
        public Nullable<long> SpecificationId { get; set; }
        public System.DateTime DueDate { get; set; }
        public bool IsScheduled { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> EstimatedUnitCost { get; set; }
        public Nullable<System.DateTime> EstimatedTotalLaborHours { get; set; }
        public Nullable<decimal> EstimatedTotalLaborCost { get; set; }
        public Nullable<decimal> EstimatedTotalMaterialCost { get; set; }
        public Nullable<decimal> OrderedBuildQuantity { get; set; }
        public Nullable<decimal> ActualBuildQuantity { get; set; }
        public Nullable<decimal> ActualUnitCost { get; set; }
        public Nullable<System.DateTime> ActualTotalLaborHours { get; set; }
        public Nullable<decimal> ActualTotalLaborCost { get; set; }
        public Nullable<decimal> ActualTotalMaterialCost { get; set; }
        public Nullable<decimal> EstimatedProfit { get; set; }
        public Nullable<System.DateTime> ScheduledStartDate { get; set; }
        public Nullable<System.DateTime> ScheduledCompletionDate { get; set; }
        public string RefNo { get; set; }
    
        public virtual ProductBuild ProductBuild { get; set; }
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Item Item { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledWorkOrder> ScheduledWorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderDetail> WorkOrderDetails { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual CurrencyExchange CurrencyExchange { get; set; }
    }
}
