//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkCenter()
        {
            this.RouterProcessDetails = new HashSet<RouterProcessDetail>();
            this.Machines = new HashSet<Machine>();
        }
    
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public string WorkCenterName { get; set; }
        public string Description { get; set; }
        public Nullable<long> ModifiedByEmployeeId { get; set; }
        public bool IsVoid { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<long> ApprovedByUserId { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsSent { get; set; }
        public bool IsForeignCurrency { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public Nullable<long> WorkCenterTypeId { get; set; }
        public Nullable<decimal> SetupLaborRate { get; set; }
        public Nullable<long> SetupLaborUnitId { get; set; }
        public Nullable<decimal> RunLaborRate { get; set; }
        public Nullable<long> RunLaborUnitId { get; set; }
        public Nullable<decimal> LaborOverhead { get; set; }
        public Nullable<decimal> MachineOverhead { get; set; }
        public Nullable<long> WorkCenterGroupId { get; set; }
        public Nullable<decimal> GeneralOverhead { get; set; }
        public string Note { get; set; }
        public Nullable<double> ScheduledHours { get; set; }
        public Nullable<double> QueuedHours { get; set; }
        public Nullable<System.DateTime> NextAvailableOn { get; set; }
        public bool IsUnlimitedResource { get; set; }
        public bool IsProductionLine { get; set; }
        public Nullable<double> WorkCenterEfficiency { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> ToolSetId { get; set; }
        public string PictureUrl { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> SpecificationId { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouterProcessDetail> RouterProcessDetails { get; set; }
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual Location Location { get; set; }
        public virtual Specification Specification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine> Machines { get; set; }
        public virtual ToolSet ToolSet { get; set; }
        public virtual WorkCenterGroup WorkCenterGroup { get; set; }
        public virtual WorkCenterType WorkCenterType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
